
import com.sun.imageio.plugins.png.RowFilter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import jdk.nashorn.internal.parser.TokenType;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author EMRE
 */
public class AnaEkran extends javax.swing.JFrame {
    DefaultTableModel model;
    Baglanti baglanti = new Baglanti();
    /** Creates new form AnaEkran */
    public AnaEkran() {
        initComponents();
        model = (DefaultTableModel)tablo.getModel();
        
        bilgileriGetirr();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        adField = new javax.swing.JTextField();
        yasField = new javax.swing.JTextField();
        telefonField = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        uyariYazisi = new javax.swing.JLabel();
        bittiYazisi = new javax.swing.JLabel();
        ekleButton = new javax.swing.JButton();
        guncelleButton = new javax.swing.JButton();
        silButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        adresField = new javax.swing.JTextField();
        kangrubuBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CORONA GECIRENLER");
        setBounds(new java.awt.Rectangle(400, 300, 0, 0));

        tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ad Soyad", "Yaş", "Telefon No", "Kan Grubu", "Adres"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabloMouseReleased(evt);
            }
        });
        tablo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabloKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabloKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablo);

        jLabel1.setText("Ad Soyad: ");

        jLabel2.setText("Yaş: ");

        jLabel3.setText("Telefon No: ");

        jLabel4.setText("Kan Grubu: ");

        yasField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yasFieldActionPerformed(evt);
            }
        });

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        uyariYazisi.setForeground(new java.awt.Color(255, 0, 0));

        bittiYazisi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bittiYazisi.setForeground(new java.awt.Color(0, 204, 51));

        ekleButton.setText("Ekle");
        ekleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleButtonActionPerformed(evt);
            }
        });

        guncelleButton.setText("Güncelle");
        guncelleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleButtonActionPerformed(evt);
            }
        });

        silButton.setText("Sil");
        silButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Adres: ");

        adresField.setToolTipText("");

        kangrubuBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bilinmiyor", "A POZITIF", "B POZITIF", "AB POZITIF", "0 POZITIF", "A NEGATIF", "B NEGATIF", "AB NEGATIF", "0 NEGATIF" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jTextField1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(yasField)
                            .addComponent(telefonField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adresField)
                            .addComponent(adField)
                            .addComponent(kangrubuBox, 0, 206, Short.MAX_VALUE))
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(uyariYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ekleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addComponent(guncelleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(silButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(bittiYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ekleButton)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guncelleButton)
                    .addComponent(telefonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(silButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(kangrubuBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(adresField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uyariYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bittiYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yasFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yasFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yasFieldActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        String arama = jTextField1.getText();
        dinamikAra(arama);
    }//GEN-LAST:event_jTextField1KeyReleased

    public boolean eklemeKontrol(){
        ArrayList<String> telefonNo = new ArrayList<String>();
        for(int i = 0 ; i<model.getRowCount() ; i++){
            telefonNo.add(String.valueOf(model.getValueAt(i, 3)));
        }
        String kucukTelefonNo = telefonField.getText().toLowerCase().trim();
        
        for(String s : telefonNo){
                if(s.toLowerCase().equals(kucukTelefonNo)){
                    int secim = JOptionPane.showConfirmDialog(this, "Eklenecek telefon numarası zaten mevcut.\nTekrar eklemek istiyor musunuz ?");
                    if(secim == JOptionPane.YES_OPTION){
                        return true;
                    }
                    else if(secim == JOptionPane.NO_OPTION){
                        return false;
                    }
                    else{
                        uyariYazisi.setText("Lütfen bir seçenek seçiniz.");
                        return false;
                    }
                }
            }
       return  true;
    }
    private void ekleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleButtonActionPerformed
        uyariYazisi.setText("");
        bittiYazisi.setText("");
        
        
        
        String adSoyad = adField.getText().trim();
        String yas = yasField.getText().trim();
        String telefon = telefonField.getText().trim();
        String kanGrubu = String.valueOf(kangrubuBox.getSelectedItem());
        String adres = adresField.getText().trim();
        
        if(adSoyad.equals("") || yas.equals("") || telefon.equals("") || kanGrubu.equals("") || adres.equals("")){
            uyariYazisi.setText("Alanlar boş bırakılamaz!");
        }
        else{
            if(telefon.length() == 11 && eklemeKontrol() && !telefon.contains(" ")){
            if(telefon.startsWith("0")){
            baglanti.bilgiEkle(adSoyad, yas, telefon, kanGrubu,adres);
            bilgileriGetirr();
            bittiYazisi.setText("Başarıyla eklendi.");
            }
            else{
                uyariYazisi.setText("Telefon numarası 0 ile başlamalıdır!");
            }
           
            
        }
            else{
                uyariYazisi.setText("Telefon numarası 11 haneli ve boşluksuz olmalıdır!");
        }
  
        }
        
    }//GEN-LAST:event_ekleButtonActionPerformed

    private void tabloMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabloMouseReleased
        int secilenRow = tablo.getSelectedRow();
        adField.setText(String.valueOf(tablo.getValueAt(secilenRow, 1)));
        yasField.setText(String.valueOf(tablo.getValueAt(secilenRow, 2)));
        telefonField.setText(String.valueOf(tablo.getValueAt(secilenRow, 3)));
        kangrubuBox.setSelectedItem(String.valueOf(tablo.getValueAt(secilenRow, 4)));
        adresField.setText(String.valueOf(tablo.getValueAt(secilenRow, 5)));
        
    }//GEN-LAST:event_tabloMouseReleased

    private void silButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silButtonActionPerformed
        bittiYazisi.setText("");
        uyariYazisi.setText("");
        int[] secilenRows = tablo.getSelectedRows();
        int secilenRow = tablo.getSelectedRow();
        
        
        
        if(secilenRow == -1){
            if(model.getRowCount() == 0){
                uyariYazisi.setText("Lütfen silmek için önce çalışan ekleyiniz");
            }
            else{
                uyariYazisi.setText("Lütfen silmek tablodan için çalışan seçiniz");
            }
        }
        else{
            for(int i : secilenRows){
                
               baglanti.bilgiSil(Integer.valueOf(String.valueOf(tablo.getValueAt(i, 0))));
               
        }
            bittiYazisi.setText("Başarıyla silindi");
            bilgileriGetirr();
        }
        
    }//GEN-LAST:event_silButtonActionPerformed

    private void guncelleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleButtonActionPerformed
        bittiYazisi.setText("");
        uyariYazisi.setText("");
        String isimsoyisim = adField.getText().trim();
        String yas = yasField.getText().trim();
        String telefon = telefonField.getText().trim();
        String kangrubu = String.valueOf(kangrubuBox.getSelectedItem());
        String adres = adresField.getText().trim();
        int secilenRow = tablo.getSelectedRow();
        if(secilenRow == -1){
            if(model.getRowCount() == 0){
                uyariYazisi.setText("Lütfen güncellemek için önce çalışan ekleyiniz.");
            }
            else{
                uyariYazisi.setText("Lütfen güncellemek için çalışan seçiniz.");
            }
        }
        else{
            if(isimsoyisim.equals("") || yas.equals("") || telefon.equals("") || kangrubu.equals("") || adres.equals("")){
                uyariYazisi.setText("Bilgiler boş bırakılamaz.");
            }
            else{
                if(guncellekontrol2() && guncellemeKontrol() && telefon.length() == 11 && !telefon.contains(" ") ){
            
                    int id = Integer.valueOf(String.valueOf(tablo.getValueAt(secilenRow, 0)));
                    baglanti.bilgiGuncelle(isimsoyisim, yas, telefon, kangrubu, adres, id);
                    bilgileriGetirr();
                    bittiYazisi.setText("Başarıyla güncellendi.");
                
            
                }
                else{
                    uyariYazisi.setText("Telefon numarası 11 haneli ve boşluksuz olmalıdır!");
                }
                
                
            }
        }
         
    }//GEN-LAST:event_guncelleButtonActionPerformed

    private void tabloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabloKeyReleased
        int secilenRow = tablo.getSelectedRow();
        adField.setText(String.valueOf(model.getValueAt(secilenRow, 1)));
        yasField.setText(String.valueOf(model.getValueAt(secilenRow, 2)));
        telefonField.setText(String.valueOf(model.getValueAt(secilenRow, 3)));
        kangrubuBox.setSelectedItem(model.getValueAt(secilenRow, 4));
        adresField.setText(String.valueOf(model.getValueAt(secilenRow, 5)));
    }//GEN-LAST:event_tabloKeyReleased

    private void tabloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabloKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DELETE){
            silButtonActionPerformed(null);
        }
    }//GEN-LAST:event_tabloKeyPressed

    public boolean guncellekontrol2(){
        ArrayList<String> isimSoyisimArrayList = new ArrayList<String>();
        int secilenRow = tablo.getSelectedRow();
        for(int i = 0 ; i<model.getRowCount() ; i++){
            isimSoyisimArrayList.add(String.valueOf(model.getValueAt(i, 1)));
        }
        String kucukisimsoyisim = adField.getText().toLowerCase().trim();
        isimSoyisimArrayList.remove(String.valueOf(tablo.getValueAt(secilenRow, 1)));
        for(String s : isimSoyisimArrayList){
                if(s.toLowerCase().equals(kucukisimsoyisim)){
                    int secim = JOptionPane.showConfirmDialog(this, "Güncellenecek kişi listede zaten mevcut.\nYine de güncellemek istiyor musunuz ?");
                    if(secim == JOptionPane.YES_OPTION){
                        return true;
                    }
                    else if(secim == JOptionPane.NO_OPTION){
                        return false;
                    }
                    else{
                        uyariYazisi.setText("Lütfen bir seçenek seçiniz.");
                        return false;
                    }
                }
            }
       return  true;
        
    }
    public boolean guncellemeKontrol(){
        ArrayList<String> telefonArrayList = new ArrayList<String>();
        int secilenRow = tablo.getSelectedRow();
        String telefonNo = telefonField.getText().trim();
        for(int i = 0 ; i<model.getRowCount();i++){
            telefonArrayList.add(String.valueOf(model.getValueAt(i, 3)));
        }
        telefonArrayList.remove(String.valueOf(tablo.getValueAt(secilenRow, 3)));
        if(telefonArrayList.contains(telefonNo)){
            int secim = JOptionPane.showConfirmDialog(this, "Güncellemek istediğiniz telefon numarası listede zaten mevcut.\nYine de güncellemek istiyor musunuz?");
            if(secim == JOptionPane.YES_OPTION){
                return true;
            }
            else if(secim == JOptionPane.NO_OPTION){
                return false;
            }
            else{
                uyariYazisi.setText("Lütfen bir seçenek seçiniz.");
                return false;
            }
        }
        return true;
        
    }
    
    public void dinamikAra(String arama){
        TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<DefaultTableModel>(model);
        tablo.setRowSorter(rowSorter);
        rowSorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + arama));;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adField;
    private javax.swing.JTextField adresField;
    private javax.swing.JLabel bittiYazisi;
    private javax.swing.JButton ekleButton;
    private javax.swing.JButton guncelleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> kangrubuBox;
    private javax.swing.JButton silButton;
    private javax.swing.JTable tablo;
    private javax.swing.JTextField telefonField;
    private javax.swing.JLabel uyariYazisi;
    private javax.swing.JTextField yasField;
    // End of variables declaration//GEN-END:variables

    public void bilgileriGetirr() {
        model.setRowCount(0);
        uyariYazisi.setText("");
        ArrayList<iletisimBilgileri> arrayiletisim = baglanti.bilgileriGetir();
        if(arrayiletisim != null){
            for(iletisimBilgileri iletisimbilgileri : arrayiletisim){
                Object[] objects =  {iletisimbilgileri.getId(),iletisimbilgileri.getIsimsoyisim(),iletisimbilgileri.getYas(),iletisimbilgileri.getTelefon(),iletisimbilgileri.getKangrubu(),iletisimbilgileri.getAdres()};
                model.addRow(objects);
            }
        }
        
        
    }
}
